// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UlrAlias.Infrastructure.Data;

#nullable disable

namespace UlrAlias.Infrastructure.Migrations
{
    [DbContext(typeof(AliasDbContext))]
    partial class AliasDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.19");

            modelBuilder.Entity("UlrAlias.Domain.Models.AliasEntry", b =>
                {
                    b.Property<string>("Alias")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Alias");

                    b.ToTable("AliasEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
