@Ulr_Alias_HostAddress = http://localhost:32769
@alias = demo

POST {{Ulr_Alias_HostAddress}}/api/aliases/
Accept: application/json

###
GET {{Ulr_Alias_HostAddress}}/api/aliases/{{alias}}/
Accept: application/json

###
GET {{Ulr_Alias_HostAddress}}/uri/{{alias}}/

###
